[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "dpcK3G40VS"
weight = 1

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "AgcyRLUGjj"
weight = 2

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "UNxn7lkosO"
weight = 3

[[main]]
name = "Talks"
pageRef = "talks"
identifier = "GDe8QwrOjY"
weight = 4

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "iIRlqF1wAb"
weight = 5
[[footer]]
none = "none"
